# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-09 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jongro_Female_20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STD_DD', models.DateField()),
                ('MCT_CAT_CD', models.IntegerField()),
                ('SEX_CD', models.CharField(max_length=1)),
                ('AGE_CD', models.IntegerField()),
                ('USE_CNT', models.IntegerField()),
                ('USE_AMT', models.IntegerField()),
                ('PM10', models.IntegerField()),
                ('PM25', models.IntegerField()),
            ],
        ),
    ]
