# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_jongro_female_30_jongro_female_40_jongro_female_50_jongro_female_60_jongro_male_20_jongro_male_30_jo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
            ],
        ),
    ]
