# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-18 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catnumber', models.IntegerField(default=0)),
                ('catname', models.CharField(max_length=20)),
            ],
        ),
    ]
